workflows:
  ios-workflow:
    name: iOS Build
    max_build_duration: 60
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
    
    # Ini penting — disable integrations default
    integrations:
      app_store_connect: none

    scripts:
      - name: Flutter pub get
        script: flutter pub get

      - name: Recreate iOS
        script: |
          rm -rf ios/
          flutter create --platforms=ios .
          ls -la ios/
          cat ios/Podfile

      - name: Precache iOS
        script: flutter precache --ios

      - name: Pod install
        script: |
          cd ios && pod install --repo-update

      - name: Build iOS
        script: |
          flutter build ipa --release --no-codesign

    artifacts:
      - build/ios/ipa/*.ipa

    publishing:
      email:
        recipients:
          - bebenmerayap@gmail.com
        notify:
          success: true
          failure: true
